Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -150,40 +150,40 @@ jobs:
         env:
           GHCR_PAT: ${{ secrets.GHCR_PAT }}
 
+      - name: Pull latest changes
+        run: git pull origin master
+
       - name: Configure Git
         run: |
           git config --global user.email "raghavenderraoch89@gmail.com"
           git config --global user.name "raghu1211"
+
+      - name: Stash uncommitted changes
+        run: git stash || echo "No changes to stash"
+
+      - name: Pull latest changes again
+        run: git pull origin master
 
       - name: Bump package version
         id: version
         run: |
           cd /home/runner/work/test/test
           NEW_VERSION=$(npm version patch | sed 's/^v//') # Increment version and strip 'v' if present
-          echo "New version is $NEW_VERSION"
           echo "::set-output name=new_version::$NEW_VERSION"
 
       - name: Check for changes before pushing
         run: |
           git diff-index --quiet HEAD || (git add package.json package-lock.json && git commit -m "Bump package version to ${{ steps.version.outputs.new_version }}" || echo "No changes to commit")
 
-      - name: Fetch latest changes from remote
-        run: git fetch origin
-
-      - name: Rebase local changes onto remote
-        run: |
-          git rebase origin/master || (git rebase --abort && exit 1)
-
       - name: Push changes
         run: |
           git push origin master
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Publish package to GitHub Packages
         run: |
           cd /home/runner/work/test/test
-          npm publish --access public || (echo "Publishing failed; attempting to overwrite." && npm publish --access public --force)
+          NEW_VERSION=$(npm version patch | sed 's/^v//') # Increment version and strip 'v' if present
+          npm publish --access public --tag $NEW_VERSION || (echo "Publishing failed; attempting to overwrite." && npm publish --access public --tag $NEW_VERSION --force)
 
 
   deploy:
